[versions]
activityKtx = "1.10.1"
activityKtxVersion = "1.10.1"
agp = "8.9.1"
cardviewVersion = "1.0.0"
comGoogleFirebaseFirebaseFirestore = "24.0.0"
firebaseAuth = "23.2.0"
firebaseAuthVersion = "21.0.5"
firebaseBom = "33.12.0"
firebaseCore = "21.1.1"
firebaseCrashlyticsVersion = "19.4.2"
firebaseFirestore = "25.1.2"
firebaseFirestoreVersion = "25.1.3"
googleFirebaseFirestore = "25.1.2"
googleFirebaseFirestoreVersion = "24.5.0"
googlePlayServicesAuth = "21.3.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lottie = "6.6.4"
material = "1.12.0"
constraintlayout = "2.2.1"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
navigationFragment = "2.8.9"
navigationUi = "2.8.9"
firebaseCrashlytics = "19.4.2"
googleGmsGoogleServices = "4.4.2"
googleFirebaseCrashlytics = "3.0.3"
playServicesAuth = "21.3.0"
firebaseDatabase = "21.0.0"
playServicesAuthVersion = "20.7.0"
roomCompiler = "2.6.1"
roomCommon = "2.6.1"

[libraries]
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
activity-ktx-v182 = { module = "androidx.activity:activity-ktx", version.ref = "activityKtxVersion" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardviewVersion" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragment" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragment" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCompiler" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-auth-v2105 = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuthVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebaseCore" }
firebase-crashlytics-v1837 = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlyticsVersion" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version = "25.1.3" }
firebase-firestore-v2400 = { module = "com.google.firebase:firebase-firestore", version.ref = "comGoogleFirebaseFirebaseFirestore" }
firebase-firestore-v2412 = { module = "com.google.firebase:firebase-firestore", version = "25.1.3" }
firebase-firestore-v2450 = { module = "com.google.firebase:firebase-firestore", version.ref = "googleFirebaseFirestoreVersion" }
firebase-firestore-v2460 = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestoreVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
play-services-auth-v2050 = { module = "com.google.android.gms:play-services-auth", version.ref = "googlePlayServicesAuth" }
play-services-auth-v2070 = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuthVersion" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }

